"""create db

迁移 ID: 0f4be1249ed9
父迁移: 
创建时间: 2024-09-13 14:15:55.377674

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0f4be1249ed9'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('nonebot_plugin_weatherpk',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('location_code', sa.String(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather')),
    info={'bind_key': ''}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    # ### end Alembic commands ###
